2020-06-24 13:46:51.900 ERROR 16356 --- [http-nio-80-exec-1] c.niit.soft.client.api.filter.JwtFilter  JwtFilter.java:58: JwtFilter过滤验证失败!
2020-06-24 13:47:00.723 ERROR 16356 --- [http-nio-80-exec-3] c.niit.soft.client.api.filter.JwtFilter  JwtFilter.java:58: JwtFilter过滤验证失败!
2020-06-24 14:00:00.348 ERROR 2012 --- [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    TaskUtils.java:95: Unexpected error occurred in scheduled task

java.lang.NullPointerException: null
	at com.niit.soft.client.api.task.SaveLog.saveLog(SaveLog.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

